### ISSUE TITLE
RAII for Storage class

### ISSUE THREAD

**Issue by whoshuu** [lysevi/nkvdb#15]
Having a public interface that allows you to "close" `Storage` complicates reasoning about the state of an instantiated `Storage` object. The destructor already calls [Close()](https://github.com/lysevi/nkvdb/blob/1bba029b7abad2b2b4b1e1a308a1c7073898e7fa/libnkvdb/storage.cpp#L59-L63), so that half of making `Storage` an RAII class is already done. Simply removing the `Close()` method from the public interface achieves a greater level of class invariance.

If you'd like some help making this change, let me know and I'll throw up a pull request.

**Comment by lysevi** [comment]
do you think that the public Close () method is contrary RAII?

**Comment by whoshuu** [comment]
Yes I do believe that. Having a public `Close()` method means a user of your library may put an instance of the `Storage` class into an unusable state. That is, a state where `m_closed` is true logically corresponds to a `Storage` object that can't do anything. Whether that's _actually_ true is ambiguous unless the user reads the implementation.

I think it's much cleaner to establish this class invariant: if you have an instance of `Storage`, you can use it. Contrapositively, you can't misuse an instance of `Storage` you don't have.

**Comment by lysevi** [comment]
in dev branch.
