### ISSUE TITLE
data loss or corruption

### ISSUE THREAD

**Issue by hroptatyr** [lysevi/nkvdb#6]
I just modified the read_write_example to insert the time values in descending order.
And also printed what's been read, to my surprise, there are time values I _didn't_ ask for in the output and, on the other hand, time values I _did_ ask for are missing.

```
diff --git a/examples/read_write_example.cpp b/examples/read_write_example.cpp
index 4c6a084..d1de1fe 100644
--- a/examples/read_write_example.cpp
+++ b/examples/read_write_example.cpp
@@ -30,7 +30,7 @@ int main(int argc, char *argv[]) {
   clock_t write_t0 = clock();
   mdb::Meas meas = mdb::Meas::empty();

-  for (int i = 0; i < 3000000; ++i) {
+  for (int i = 3000000; i-- > 0;) {
     meas.value = i;
     meas.id = i % 10;
     meas.source = meas.flag = 0;
@@ -47,11 +47,14 @@ int main(int argc, char *argv[]) {
   clock_t read_t0 = clock();

   mdb::Meas::MeasList output;
-  auto reader = ds->readInterval(0, writes_count);
+  auto reader = ds->readInterval(3, 30);

   // or meases->readAll(&output);
   while (!reader->isEnd()) {
          reader->readNext(&output);
+         for (auto i = output.cbegin(); i != output.cend(); ++i) {
+                 printf("got time %lu\n", i->time);
+         }
   }
```

So I asked for times between 3 and 30 and got:

```
write 3000000 values...
write time: 2.84058
read all values...
got time 0
got time 1
got time 2
got time 24
got time 3
read time :0.192736
```

**Comment by hroptatyr** [comment]
I'm sorry but what is `ds->readInterval(3, 30)` supposed to do?  I assumed it would give me data points written at time 3, 4, ..., 30.  But it doesn't.

```
write 3000000 values...
write time: 1.8246
read all values...
got time 0
got time 1
got time 2
got time 3
got time 4
got time 5
got time 6
got time 7
got time 8
got time 9
got time 10
got time 11
got time 12
got time 13
got time 14
got time 15
got time 16
got time 17
got time 18
got time 19
got time 20
got time 21
got time 22
got time 23
got time 24
got time 25
got time 26
got time 27
got time 28
got time 29
got time 30
```

**Comment by lysevi** [comment]
if you write measurement A1 exists in time T_0 and A2 in T_2, but you read in time T_1, you must get values of A1 because  still exists in time T_1. if after them you write new value of A1 in time T_3 and read in time T_4, then you get A_1 with T_3 time

**Comment by hroptatyr** [comment]
Exactly, that's why it's still broken.  Your example writes a measurement at time 0, 1, 2, 3, ...   Afterwards I'm interested in time 3, and you show me measurements from time 0, 1, and 2.  That's just plain wrong.

**Comment by lysevi** [comment]
you ar right.

**Comment by lysevi** [comment]
just example.
you write meases to storage 
{id=1,time=0},{id=1,time=1}{id=1,time=2}{id=1,time=3}{id=1,time=4}...{id=1,time=30}

you read from 3 to 30. What must storage return ?

**Comment by hroptatyr** [comment]
Well at least
{id=1,time=3}{id=1,time=4}...{id=1,time=29}

about the item at time=30 you could argue that you want a half-open interval (from inclusive, to exclusive) so that you don't get the item twice if you query with `readInterval(30, 60)` in the next step, but that's up to you and should be documented somewhere somehow.

**Comment by lysevi** [comment]
ok. if you write

{id=1,time=0},{id=2,time=1}{id=3,time=2}{id=4,time=3}{id=5,time=4}...{id=30,time=30}
you read from 3 to 30. What must storage return ?

**Comment by hroptatyr** [comment]
All of them, correct.

**Comment by lysevi** [comment]
a while, in case 
{id=1,time=0},{id=1,time=1}{id=1,time=2}{id=1,time=3}{id=1,time=4}...{id=1,time=30}
storage return {id=1,time=2}{id=1,time=3}...{id=1,time=29}

in future, when i implement true indexes, you can customize the behavior of the readInterval
